CREATE TABLE workers_AUD
(
    id               UUID,
    name             VARCHAR(100),
    password         VARCHAR(50),
    REV              INTEGER,
    deleted          BOOLEAN,
    created_at       DATE,
    last_modified_at DATE,
    REVTYPE          SMALLINT,
    PRIMARY KEY (id, REV)
);

CREATE TABLE revinfo
(
    rev      INTEGER GENERATED BY DEFAULT
        AS IDENTITY ( START WITH 1 ),
    revtstmp BIGINT,
    PRIMARY KEY (rev)
);

ALTER TABLE workers_AUD
    ADD CONSTRAINT
        fkllaf9w93qaiooguo8mfvwtwbg
        FOREIGN KEY (REV) REFERENCES revinfo